name: Scheduled health check

on:
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the app's health
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: https://amadeuspokedex.herokuapp.com/health
          follow-redirect: no 
          max-attempts: 3
          retry-delay: 10s