name: Scheduled health check

on:
  push:
    branches:
      - pull_request_trigger

jobs:
  health_check:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the app is still running
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: https://amadeuspokedex.herokuapp.com/health
          follow-redirect: no 
          max-attempts: 3
          retry-delay: 10s